### ISSUE TITLE
Abandon project?

### ISSUE THREAD

**Issue by arafatx** [opentape/opentape#4]
Looks like the latest version is from 2008. 8 years never updated ? I'm the fan of opentape few years back.

**Comment by slambert** [comment]
@arafatx There are contributions as recent as 2014: https://github.com/opentape/opentape/network

Though I'd love to see a release as much as you...

**Comment by MaxPleaner** [comment]
Well as a new user I can confirm it still works.

**Comment by princeboucher** [comment]
Does it play for anyone on mobile? I can use it on my desktop, but mobile seems to be broken? Can we fork a solution w/ an HTML 5 audio player?

**Comment by zproc** [comment]
I'd love an updated version with an HTML 5 player, i still have a backup of my old mixtapes with Opentape and was thinking for a while of uploading them again... I forgot it was using Flash. (That I've been avoiding for some years now.) - i was just checking here in case of potential vulnerabilities / see if there were any updates...

**Comment by opentape** [comment]
Removed flash, fixed a few things. This might get your tapes running again. This is some super-ancient PHP so unfortunately could have some security bugs too. I might have a moment to clean it up a bit.

This whole thing needs to be rewritten in like a 100 line JS project :)
